spring:
  datasource:
    url: jdbc:h2:mem:forumhub
    driver-class-name: org.h2.Driver
    username: forumhub
    password: forumhub
  jpa:
    hibernate:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  error:
    include-stacktrace: never